name: lipyphilic
channels:
    - conda-forge
    - defaults
dependencies:
    - python >=3.6,<=3.9
    - numpy >=1.16,<=1.21
    - scipy >=1.5
    - pandas >=1.2.0
    - mdanalysis >=1.0
    - freud=2.4.1
    - tqdm
    - pip
    - pip:
        - lipyphilic
