name: lipyphilic
channels:
    - conda-forge
    - defaults
dependencies:
    - python >=3.6,<=3.9
    - numpy >=1.16,<1.20
    - numba
    - scipy >=1.5
    - mdanalysis >=1.0.1
    - freud
    - rowan
    - tqdm
    - pip
    - pip:
        - lipyphilic
